#!/bin/sh
me=$(basename "$0")
my_dir=$(dirname "$0")

action=${1:-install}

case "$action" in
  install|reinstall|uninstall) ;;
  *) echo "Usage: $me [install|reinstall|uninstall]"; exit 1 ;;
esac

cd "$my_dir"

managed_by_stow=$(find . -maxdepth 1 -mindepth 1 -type d | sed 's|^\./||')
for package in $managed_by_stow; do
  case "$action" in
    install)   stow -t "$HOME" -S "$package" ;;
    reinstall) stow -t "$HOME" -R "$package" ;;
    uninstall) stow -t "$HOME" -D "$package" ;;
  esac
done

cd ~-
