#!/bin/sh
me=$(basename $0)
my_dir=$(dirname "$0")

action=${1:-install}

if [ "$action" != "install" ] && [ "$action" != "uninstall" ]; then
  echo "Usage: $me [install|uninstall]"
fi

cd $my_dir

managed_by_stow=$(find . -type d -maxdepth 1 -mindepth 1 | sed 's|^\./||')
for package in $managed_by_stow; do
  if [ "$action" == "install" ]; then
    stow -t $HOME -R $package
  else
    stow -t $HOME -D $package
  fi
done

cd ~-
