-- Ident and line wrapping
vim.opt.expandtab = true
local indent = 2
vim.opt.shiftwidth = indent
vim.opt.tabstop = indent
vim.opt.breakindent = true
vim.opt.linebreak = true
vim.opt.showbreak = "↪ "

-- Clipboard
vim.opt.clipboard = "unnamed"

-- Search and replace
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.inccommand = "split"

-- Mouse only in visual and normal
vim.opt.mouse = "nv"

-- Keep N lines above and below cursor
vim.opt.scrolloff = 4

-- Split below and to the right
vim.opt.splitbelow = true
vim.opt.splitright = true

-- Read tags generated by git hook
vim.opt.tags:append { ".git/tags" }

-- Whitespace
vim.opt.list = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }

-- Decrease update time
vim.opt.updatetime = 250
vim.opt.timeoutlen = 300

-- Record undo stack
vim.opt.undofile = true

-- Hybrid line numbers
vim.opt.number = true
vim.opt.relativenumber = true

-- Always display sign column, so that it doesn't jump
vim.opt.signcolumn = "yes"

-- Folds
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldtext = ""
vim.opt.foldmethod = "expr"
vim.opt.foldenable = false -- `zi` to toggle

-- Completion (TODO: can't remember what this does exactly)
vim.opt.completeopt = "menu,menuone,noselect"

-- Wildmenu (TODO: can't remember what this does exactly)
vim.opt.wildmode = "longest:full,full"

-- Allow project specific config
vim.opt.exrc = true

-- Highlight on yank
vim.api.nvim_create_autocmd("TextYankPost", {
  group = vim.api.nvim_create_augroup("HighlightOnYank", {}),
  pattern = "*",
  callback = function() vim.highlight.on_yank() end,
})

-- Scale splits when resizing terminal
vim.api.nvim_create_autocmd("VimResized", {
  group = vim.api.nvim_create_augroup("ResizeSplitsOnWinResize", {}),
  pattern = "*",
  command = "wincmd =",
})

-- Cursorline only in active buffer stolen from TJ
vim.opt.cursorline = true -- Highlight the current line
local set_cursorline_group = vim.api.nvim_create_augroup("CursorLineControl", {})
local set_cursorline = function(event, value)
  vim.api.nvim_create_autocmd(event, {
    group = set_cursorline_group,
    callback = function() vim.opt_local.cursorline = value end,
  })
end
set_cursorline("WinLeave", false)
set_cursorline("WinEnter", true)

-- No line numbers, start terminal in insert mode
vim.api.nvim_create_autocmd({ "BufEnter", "WinEnter", "TermOpen" }, {
  group = vim.api.nvim_create_augroup("TerminalTweaks", {}),
  pattern = "term://*",
  callback = function()
    vim.opt_local.number = false
    vim.opt_local.relativenumber = false
    vim.cmd.startinsert()
  end,
})

-- Handle big files with grace
local is_big_file = function(filepath)
  local file_is_readable = vim.fn.filereadable(filepath) == 1
  if not file_is_readable then
    return false
  end
  local lines = vim.fn.readfile(filepath)
  local line_count = #lines
  local first_line_length = #(lines[1] or "")
  return line_count > 50000 or first_line_length > 1000
end

vim.api.nvim_create_autocmd({ "BufReadPre", "FileReadPre" }, {
  group = vim.api.nvim_create_augroup("HandleBigFiles", {}),
  callback = function()
    if is_big_file(vim.fn.expand "%") then
      vim.cmd.syntax "off"
      vim.cmd.filetype "off"
      vim.cmd "TSBufDisable highlight"
      vim.opt_local.foldmethod = "manual"
      vim.opt_local.undofile = false
      vim.opt_local.swapfile = false
      vim.opt_local.loadplugins = false
    end
  end,
})
