schemaVersion = 1

[catalogConfiguration]
customFolders = []
scriptsDirectories = []

    [[catalogConfiguration.folderDepthOverrides]]
    catalogIdentifier = 'TunaCore.UserFoldersCatalog'
    depthRawValue = 1

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[[hotkeys.custom]]
id = '599AA7D2-CE16-4E91-A977-3B53B3DFC630'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.Bear'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 20
    carbonModifiers = 2048

[[hotkeys.custom]]
id = '5E3BF8B7-FEB3-4659-AD70-94A94A39A59C'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Run'
    subjectIdentifier = 'TunaSystem.WindowManagementCatalog.Right Half'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 37
    carbonModifiers = 4352

[[hotkeys.custom]]
id = '6764304D-C6E7-42BC-947E-159B31350897'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Run'
    subjectIdentifier = 'TunaSystem.WindowManagementCatalog.Left Half'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 4
    carbonModifiers = 4352

[[hotkeys.custom]]
id = '6ADB80DD-84F9-422C-A739-C5B1DFCC70CD'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.kitty'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 18
    carbonModifiers = 2048

[[hotkeys.custom]]
id = '73908780-DD80-4C18-A5E0-5F32B8FC078C'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.AllApplicationsCatalog.Claude'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 10
    carbonModifiers = 2048

[[hotkeys.custom]]
id = '8053482D-A4AD-49B2-A4D7-60BC3B62B9F0'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Open'
    subjectIdentifier = 'TunaCore.SystemApplicationsCatalog.Safari'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 19
    carbonModifiers = 2048

[[hotkeys.custom]]
id = 'A4E23CC0-F7F2-4CC6-8EE1-D57F4DED6616'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Run'
    subjectIdentifier = 'TunaSystem.WindowManagementCatalog.Next Display'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 48
    carbonModifiers = 4352

[[hotkeys.custom]]
id = 'F92F8188-38E3-41D7-9D9B-A06091904AAD'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'TunaCore.CommonActionsCatalog.Run'
    subjectIdentifier = 'TunaSystem.WindowManagementCatalog.Maximize'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 3
    carbonModifiers = 4352

[[leaderMode.bindings]]
key = 's'
url = 'tuna://run/path.%252FApplications%252FSafari.app/Open'

[[leaderMode.bindings]]
key = 't'
url = 'tuna://run/path.%252FSystem%252FApplications%252FUtilities%252FTerminal.app/Open'

[[leaderMode.bindings]]
key = 'f'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[leaderMode.bindings]]
key = 'm'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[leaderMode.bindings]]
key = 'n'
url = 'tuna://run/path.%252FSystem%252FApplications%252FNotes.app/Open'

[[leaderMode.bindings]]
key = 'd'
url = 'tuna://run/path.%252FUsers%252Fmuchzill4%252FDownloads/Open'

[[leaderMode.bindings]]
key = 'h'
url = 'tuna://run/path.%252FUsers%252Fmuchzill4/Open'

[settings]
clipboardHistoryEnabled = false
resultListNavigationBindings = 'macOSStandard'
shelfCatalogEnabled = false
themeIdentifier = 'com.brnbw.tuna.themes.default'