#!/usr/bin/env bash
SOURCE_FILE=$1
SOURCE_FILE_NAME=$(basename "$1")

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT
SHADOW_FILE=$TMPDIR/$SOURCE_FILE_NAME
cat > $SHADOW_FILE

mypy --show-column-numbers --follow-imports=silent --shadow-file $SOURCE_FILE $SHADOW_FILE $SOURCE_FILE
