#!/bin/bash
if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/Dev/* -maxdepth 1 -mindepth 1 -type d`
    selected=`echo "$items" | fzf-tmux -p`
fi

if [ -z "$selected"]; then
    exit 1
fi

dirname=`basename $selected`

tmux switch-client -t $dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
