version: 2
root-markers:
  - .git/

tools:
  generic-prettier: &generic-prettier
    format-command: "prettier"

  python-flake8: &python-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  python-mypy: &python-mypy
    lint-command: "mypy-stdin ${INPUT} -"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"
    lint-stdin: true

  python-black: &python-black
    format-command: "black -"
    format-stdin: true

languages:
  python:
    # - <<: *python-flake8
    # - <<: *python-black
    - <<: *python-mypy

  markdown:
    - <<: *generic-prettier

  yaml:
    - <<: *generic-prettier
