# Homebrew
# --------------------
#tap Homebrew/brewdler
tap 'homebrew/dupes'

brew 'bash'
brew 'ctags'
brew 'curl'
brew 'fish'
brew 'git'
brew 'grep --with-default-names'
brew 'httpie'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'openssl'
brew 'rbenv --HEAD'
brew 'pyenv'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'

# Cask
# --------------------
cask 'dropbox'
cask 'flash'
cask 'forklift'
cask 'iterm2'
cask 'skype'
cask 'spectacle'
cask 'spotify'
cask 'steermouse'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'ynab'

# Appstore & manual
# --------------------
#
# 1/ Chrome and Firefox 1password integration requires
#    them to be installed in /Applications directory
#
# 1password, dash, sunrise, clear, notability, chrome, firefox, keynote, numbers, pages
