# CRAP ALERT: Brewfiles and cask is still not 100% nice,
# this will fail if I already have something tapped or installed with cask

# Homebrew
# --------------------
tap homebrew/dupes
tap homebrew/php

install caskroom/cask/brew-cask
install ansible
install ctags
install curl
install fish --HEAD
install git
install grep --default-names
install mysql
install nginx
install node
install openssl
install rbenv --HEAD
install reattach-to-user-namespace
install ruby-build
install sqlite
install tmux
install vim

install boris
install php55
install php55-apcu
install php55-mcrypt
install php55-xdebug
install composer

# Cask
# --------------------
# cask install dash
# cask install firefox
# cask install sequel-pro
cask install alfred
cask install dropbox
cask install flash
cask install google-chrome
cask install iterm2
cask install mailbox
cask install monotype-skyfonts
cask install skype
cask install slate
cask install spotify
cask install steermouse
cask install transmission
cask install vagrant
cask install virtualbox
cask install vlc
cask install ynab
