include doubletrouble.conf

font_family Rec Mono Custom
font_size 12.5
text_composition_strategy 5.0 0

draw_minimal_borders no
window_border_width 1px
confirm_os_window_close 1
cursor_blink_interval 0
enable_audio_bell no
enabled_layouts tall,vertical,stack
hide_window_decorations titlebar-only
macos_option_as_alt yes
macos_show_window_title_in none
macos_titlebar_color background
tab_bar_min_tabs 1
tab_bar_style custom
tab_title_template "{title}{' 🔎' if layout_name == 'stack' else ''}"
allow_remote_control yes
listen_on unix:/tmp/mykitty

map cmd+enter launch --cwd=oldest
map cmd+shift+enter launch --type=background --allow-remote-control fish -c kitty-launch-session-root
map cmd+t launch --type=tab --cwd=oldest
map cmd+shift+t launch --type=background --allow-remote-control fish -c 'kitty-launch-session-root tab'
map cmd+p launch --type=tab --allow-remote-control fish -c kitty-sessions
map cmd+shift+p launch --type=tab --allow-remote-control fish -c kitty-projects
map cmd+l nth_os_window -1
map cmd+z toggle_layout stack
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+d detach_window new-tab
map cmd+m create_marker
map cmd+shift+m remove_marker

map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l
